// CONSTANTS FOR BASIC THINGS IN SDL THAT DOESN'T EXIST YET
// IN THE RUST BINDINGS, KEEP THINGS SIMPLE
pub const SDL_QUIT: u32 = 0x100;
pub const SDL_WINDOW_BORDERLESS: u32 = 0x00000010;

// SDL KEYPRESS CONSTANTS
pub const SDL_KEYDOWN: u32 = 0x300;

// Escape Key
pub const SDLK_ESCAPE: i32 = 0x1B;
